### ISSUE TITLE
crash after instaling the mod

### ISSUE THREAD

**Issue by SilexW** [the-realest-stu/DynamicTrees-BOP#41]
got a crash when trying to load the game after instaling the mod.
follows the report.

https://pastebin.com/rLXbRc9W

any idea on how to fix? thanks

**Comment by the-realest-stu** [comment]
Wow, I've actually never seen that happen before.
The problem is that Minecraft 1.12 can only have a maximum of 4096 different kinds of blocks registered (actually for vanilla it's only 256, but Forge extends it to 4096). You seem to have quite a few mods that add quite a few blocks, and adding DTBOP was the tipping point.
You can either remove some mods from your pack, or try messing with the configs to see if you can disable some modded blocks.
